// Datenbank der Modulbeschreibungen (Zusatztexte)
const BESCHREIBUNGEN_DB = {
  "Aktivierung": "Zusatz: Lebenslauf aufbereiten, Zugangsdaten EsoJob vermitteln und Teilnehmer im Projekt positionieren.",
  "Infoveranstaltung „Bali“": "Zusatz: Den Kunden über das Projekt informieren und anleiten sich aktiv im Projekt „BALI“ zu bewegen.",
  "Aktivierung Exklusiv": "Zusatz: Lebenslauf aufbereiten, Zugangsdaten EsoJob vermitteln und Teilnehmer im Projekt positionieren.",
  "Aktivierung und Unterstützung": "Zusatz: Abklärung des Bewerberpotentials und Erarbeitung realistischer beruflicher Perspektiven.",
  "Arbeitsrecht / Arbeitszeugnis und Gehaltsverhandlung": "Zusatz: Richtlinien des Arbeitsrechtes, Gehaltsverhandlungen und Aufbau eines Arbeitszeugnisses kennenlernen.",
  "Arbeit 4.0": "Zusatz: Digitalisierung in diversen Bereichen, hauptsächlich industriell.",
  "Assessment und Eignungstest, Fachkräfte": "Zusatz: Testverfahren kennenlernen, IQ aktivieren und konstruktiver auf Arbeitgeber zugehen.",
  "Bewerbungscoaching": "Zusatz: Unterstützung durch Suchstrategien und Netzwerkstrategien.",
  "BA Bewerbermanagement": "Zusatz: Nutzung der Jobbörse, KURSNET/BERUFENET und e-Services der Bundesagentur.",
  "Berufliche Kommunikation": "Zusatz: Kommunikationspsychologie, Strategien im Alltag und Konfliktlösungstraining.",
  "Bewusster Umgang mit sozialen Medien": "Zusatz: Umgang mit Smartphone und Internetnutzung sowie Vermeidung von Abhängigkeiten.",
  "Digital Works - Word Anfänger": "Zusatz: Basics zum selbständigen Erstellen und Bearbeiten von Textdokumenten.",
  "Digital Works Word Pro(2/2)": "Zusatz: Aufbaukurs für Fortgeschrittene zur Optimierung beruflicher Tätigkeiten.",
  "Digital Works - Excel Anfänger": "Zusatz: Erwerb grundlegender Kenntnisse in der Tabellenbearbeitung.",
  "Digital Works Excel Pro(1/2)": "Zusatz: Optimierung der Excel-Kenntnisse für den beruflichen Einsatz.",
  "Eigenrecherche": "Zusatz: Stellenrecherche mit Coach-Begleitung und Anwenden von Vermarktungsstrategien.",
  "Einzelcoaching": "Zusatz: Einzelgespräch zur Überprüfung der bisherigen Strategie und neuer Ansatzmöglichkeiten.",
  "Eigenrecherche / Vortrag": "Zusatz: Vorstellung von Zeitarbeitsunternehmen zur Reduzierung von Ablehnungsverhalten.",
  "Entspannungsreise": "Zusatz: Körper und Kopf entspannen, um mit neuer Energie in den Bewerbungsdruck zu gehen.",
  "Fotoshooting": "Zusatz: Erstellung eines zeitgemäßen Bewerbungsfotos zur visuellen Darstellung.",
  "Fachkräfte Arbeitsrecht/Arbeitszeugnis": "Zusatz: Richtlinien des Arbeitsrechtes, Pflichten der Arbeitnehmer und Gehaltsverhandlungen.",
  "Fachkräfte VG": "Zusatz: Training für Vorstellungsgespräche durch Rollenübungen, Präsentationen und Fallstudien.",
  "Gewaltfreie Kommunikation 1/2": "Zusatz: Empathisches Zuhören und wertschätzendes Sprechen für entspannten betrieblichen Umgang.",
  "Gesundheit / Ernährung": "Zusatz: Verbesserung des Wohlbefindens für einen vitaleren Auftritt in Gesprächen.",
  "Gesundheit/Ergonomie": "Zusatz: Optimierung der Passung zwischen Mensch und Arbeit zur Gesundheitsförderung.",
  "Job-Speed-Dating 2025": "Zusatz: Über Zeitarbeit im Sprungbrett-Verfahren in dauerhafte Beschäftigung finden.",
  "Job-Speed-Dating 2026": "Zusatz: Über Zeitarbeit im Sprungbrett-Verfahren in dauerhafte Beschäftigung finden.",
  "Kompetenzfeststellung": "Zusatz: Stärken-Schwächen-Analyse mit beruflichen Kompetenzen für Unterlagen erweitern.",
  "Konflikt und Mobbing": "Zusatz: Thematisierung von Mobbing-Erleben und Bearbeitung schwieriger Situationen.",
  "Konfliktvermeidung/wertschätzende Kommunikation": "Zusatz: Prävention durch gewaltfreien Umgang im persönlichen und beruflichen Umfeld.",
  "Kontaktmanagement, Telefonakquise": "Zusatz: Hilfestellung zur telefonischen Bewerbung durch erfahrene Coaches.",
  "Konzentrationsübungen": "Zusatz: Fokus verbessern und Ablenkungen ausblenden als Vorbereitung auf das Bewerbungsverfahren.",
  "Mobiflex": "Zusatz: Minderung von Mobilitäts-Beeinträchtigungen durch Recherchetechniken und Apps.",
  "Potenzialerkennung": "Zusatz: Erarbeiten der eigenen Fähigkeiten in Bezug auf Einsatzmöglichkeiten.",
  "Stärken- und Schwächenanalyse": "Zusatz: Auseinandersetzung mit Zielen und Schlüsselqualifikationen aus dem Berufsfeld.",
  "Selbstvermarktung": "Zusatz: Erarbeitung eines Leistungsprofils und Suche nach beruflichen Alternativen.",
  "Stressmanagement 1/2": "Zusatz: Bewältigungsstrategien für Stresserleben und Suche nach Präventionskursen.",
  "Stress/Burnout/Sucht-Prävention 1/2": "Zusatz: Frühzeitiges Erkennen von Herausforderungen und Kontakt zu Fachpersonal.",
  "Sozialversicherung": "Zusatz: Grundlegende Informationen zur Kranken-, Pflege- und Rentenversicherung.",
  "Umgang mit sozialen Medien": "Zusatz: Sensibilisierung für Internetnutzung und Smartphone-Abhängigkeiten.",
  "Vorstellungsgespräch": "Zusatz: Ablauf eines positiven Gesprächs, Rollenübungen und Fallstudien.",
  "Wirtschaftlicher Umgang mit Geld": "Zusatz: Budgetplanung, Haushaltsbuch und Beratung zur Vermeidung von Schulden.",
  "Zeitmanagement": "Zusatz: Vereinbarkeit von Beruf und Familie sowie individuelle Parameter zur Umstellung.",
  "Zeitmanagement / Stressmanagement": "Zusatz: Umgang mit Deadlines und Familienalltag zur Vermeidung von Burnout."
};
};